cv-app:
  resources-path: ${APP_RESOURCE_PATH}
  main-url: ${APP_MAIN_URL}

pdf:
  filename: ${PDF_FILENAME}
  fontname: ${PDF_FONTNAME}

locales:
  langs: ${langs}
  links: ${links}
  default-lang: ${DEFAULT_LANG}
  default-link: ${DEFAULT_LINK}

not-found:
  site: ${NOT_FOUND_SITE}
