cv-app:
  resources-path: ${APP_RESOURCE_PATH}

pdf:
  filename: ${PDF_FILENAME}
  fontname: ${PDF_FONTNAME}

locales:
  langs: ${langs}
  links: ${links}
  default-lang: ${DEFAULT_LANG}
  default-link: ${DEFAULT_LINK}
